# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(default='your own name', max_length=30)),
                ('last_name', models.CharField(default='your surname', max_length=30)),
                ('other_names', models.CharField(default='other name', max_length=255)),
                ('username', models.CharField(max_length=30)),
                ('staff_id', models.CharField(max_length=7, unique=True)),
                ('bio', models.TextField()),
                ('department', models.CharField(max_length=30)),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now)),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
