# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tict', '0002_auto_20170105_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('staff_id',)},
        ),
    ]
